In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import hdbscan
from sklearn.decomposition import PCA
from scipy.spatial.distance import pdist, squareform
from sklearn.covariance import MinCovDet
import os
import time
from sklearn.utils.extmath import fast_logdet

In [4]:
import numpy as np
import pandas as pd
import hdbscan
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd 
import os

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA  # <-- Missing import
import matplotlib.pyplot as plt
#data load
raw_counts = pd.read_csv("Final data_.csv", index_col=0)

In [5]:
raw_counts.columns = raw_counts.columns.str.replace(r'^(CONTROL|TREATMENT).*', r'\1', regex=True)
print("\nCleaned columns:")
print(raw_counts.columns)

Cleaned columns:
Index(['CONTROL', 'CONTROL', 'CONTROL', 'TREATMENT', 'TREATMENT', 'TREATMENT',
       'CONTROL', 'CONTROL', 'CONTROL', 'TREATMENT',
       ...
       'CONTROL', 'CONTROL', 'TREATMENT', 'TREATMENT', 'CONTROL', 'CONTROL',
       'TREATMENT', 'TREATMENT', 'CONTROL', 'CONTROL'],
      dtype='object', length=202)

In [8]:
raw_counts.describe()

,CONTROL,CONTROL,CONTROL,TREATMENT,TREATMENT,TREATMENT,CONTROL,CONTROL,CONTROL,TREATMENT,...,CONTROL,CONTROL,TREATMENT,TREATMENT,CONTROL,CONTROL,TREATMENT,TREATMENT,CONTROL,CONTROL
count,28581.000000,28581.000000,28581.000000,28581.000000,28581.000000,28581.000000,28581.000000,28581.000000,28581.000000,28581.000000,...,28581.000000,2.858100e+04,28581.000000,28581.000000,28581.000000,28581.000000,28581.000000,28581.000000,28581.00000,28581.000000
mean,337.338861,258.200518,354.676218,310.343165,286.769287,243.725832,244.345719,277.621392,113.155313,143.355726,...,955.742521,2.310960e+03,426.131731,490.452783,358.515167,395.439348,426.872328,376.962702,451.02904,390.957979
std,2130.644672,2007.501541,1656.052777,3108.427121,2455.910174,2112.309010,1834.986168,2245.295346,1079.189744,1826.177229,...,8928.896065,2.418052e+04,1871.779305,1840.755694,1415.776448,1415.100989,1631.919288,1548.640672,2122.24816,1668.899471
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
50%,31.000000,19.000000,40.000000,33.000000,30.000000,26.000000,22.000000,36.000000,10.000000,13.000000,...,75.000000,1.890000e+02,63.000000,83.000000,57.000000,57.000000,72.000000,61.000000,48.00000,62.000000
75%,263.000000,180.000000,294.000000,223.000000,215.000000,182.000000,183.000000,234.000000,80.000000,96.000000,...,514.000000,1.202000e+03,346.000000,432.000000,308.000000,323.000000,386.000000,331.000000,314.00000,319.000000
max,255372.000000,283232.000000,155208.000000,448765.000000,349440.000000,291930.000000,259124.000000,338622.000000,160190.000000,280931.000000,...,785636.000000,1.940297e+06,88967.000000,81162.000000,66518.000000,80289.000000,81983.000000,82531.000000,91748.00000,93326.000000

In [9]:
raw_counts.head()
raw_counts.info

<bound method DataFrame.info of               CONTROL  CONTROL  CONTROL  TREATMENT  TREATMENT  TREATMENT  \
GeneID
LOC101497325        3        1        4          2          0         10
LOC101488339       66       34       95         78         84         85
LOC101488545       93       59       90         60         45         64
LOC101497647      154      136      153        156        148         65
LOC101489113      729      534      760        502        604        441
...               ...      ...      ...        ...        ...        ...
CiarC_p072          0        0        0          0          0          0
CiarC_p073          0        0        0          0          0          0
CiarC_t029          0        0        0          0          0          0
CiarC_p074          0        0        0          0          0          0
CiarC_p075          0        0        0          0          0          0

              CONTROL  CONTROL  CONTROL  TREATMENT  ...  CONTROL  CONTROL  \
GeneID                                              ...
LOC101497325        1        3        3          1  ...        1       15
LOC101488339      107       89       12         40  ...       99       97
LOC101488545       65       55       18         36  ...      304      395
LOC101497647       88       68       12         13  ...      418      604
LOC101489113      338      524      231        257  ...     1120     4464
...               ...      ...      ...        ...  ...      ...      ...
CiarC_p072          0        0        0          0  ...        0        0
CiarC_p073          0        0        0          0  ...        0        0
CiarC_t029          0        0        0          0  ...        0        0
CiarC_p074          0        0        0          0  ...        0        0
CiarC_p075          0        0        0          0  ...        0        0

              TREATMENT  TREATMENT  CONTROL  CONTROL  TREATMENT  TREATMENT  \
GeneID
LOC101497325          6         26        9       10         16         11
LOC101488339         12         35       17       16         46         38
LOC101488545         35         54       31       31         53         45
LOC101497647         67         88       19      155        101         99
LOC101489113       1306       2126     1251     1261       1555       1120
...                 ...        ...      ...      ...        ...        ...
CiarC_p072            0          0        0        0          0          0
CiarC_p073            0          0        0        0          0          0
CiarC_t029            0          0        0        0          0          0
CiarC_p074            0          0        0        0          0          0
CiarC_p075            0          0        0        0          0          0

              CONTROL  CONTROL
GeneID
LOC101497325        6        4
LOC101488339        1       32
LOC101488545       34       48
LOC101497647       31       73
LOC101489113     1263     1159
...               ...      ...
CiarC_p072          0        0
CiarC_p073          0        0
CiarC_t029          0        0
CiarC_p074          0        0
CiarC_p075          0        0

[28581 rows x 202 columns]>

In [10]:
filtered_df = raw_counts[raw_counts.ne(0).any(axis=1)]

In [14]:

filtered_df.describe()

,CONTROL,CONTROL,CONTROL,TREATMENT,TREATMENT,TREATMENT,CONTROL,CONTROL,CONTROL,TREATMENT,...,CONTROL,CONTROL,TREATMENT,TREATMENT,CONTROL,CONTROL,TREATMENT,TREATMENT,CONTROL,CONTROL
count,27038.000000,27038.000000,27038.000000,27038.000000,27038.000000,27038.000000,27038.000000,27038.000000,27038.000000,27038.000000,...,27038.000000,2.703800e+04,27038.000000,27038.000000,27038.000000,27038.000000,27038.000000,27038.000000,27038.000000,27038.000000
mean,356.590058,272.935461,374.916821,328.053776,303.134588,257.634736,258.289999,293.464642,119.612841,151.536726,...,1010.284673,2.442842e+03,450.450144,518.441860,378.974850,418.006213,451.233005,398.475146,476.768289,413.269103
std,2189.031532,2063.016245,1700.422568,3194.986213,2524.034620,2170.922220,1885.666161,2307.468570,1109.209001,1877.233970,...,9177.145058,2.485445e+04,1921.601146,1888.715175,1452.949159,1451.675082,1674.560907,1589.523700,2179.152261,1713.171695
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,1.000000,3.000000e+00,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,43.000000,27.000000,55.000000,45.000000,42.000000,36.000000,32.000000,48.000000,14.000000,18.000000,...,101.000000,2.490000e+02,79.000000,102.000000,73.000000,72.000000,93.000000,79.000000,64.000000,80.000000
75%,285.000000,199.000000,319.000000,243.000000,232.000000,196.000000,199.000000,253.000000,87.000000,104.000000,...,559.000000,1.310750e+03,375.000000,468.000000,333.000000,349.000000,416.000000,361.000000,342.000000,342.000000
max,255372.000000,283232.000000,155208.000000,448765.000000,349440.000000,291930.000000,259124.000000,338622.000000,160190.000000,280931.000000,...,785636.000000,1.940297e+06,88967.000000,81162.000000,66518.000000,80289.000000,81983.000000,82531.000000,91748.000000,93326.000000

Imports and directory creations

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import time
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.covariance import MinCovDet
import hdbscan
from scipy import linalg

def fast_logdet(matrix):
    """Compute log determinant efficiently"""
    return 2 * np.sum(np.log(np.diag(linalg.cholesky(matrix))))

# Create output directory
output_dir = "final_results/distance_metric_comparison_again_for_FOR_3k_GENES/check"
os.makedirs(output_dir, exist_ok=True)

In [ ]:
DATA normalization and extraction of top variable genes

In [15]:

# 1. Data preparation
normalized_data = np.log2(filtered_df + 1)  # Log2 transform with pseudocount

# 2. Select top variable genes
gene_variability = normalized_data.std(axis=1)
top_genes = gene_variability.sort_values(ascending=False).head(3000).index
top_variable_data = normalized_data.loc[top_genes]

print(f"Top variable genes shape: {top_variable_data.shape}")

top_variable_data = pd.DataFrame(
    StandardScaler().fit_transform(top_variable_data),
    index=top_genes,  # CORRECTED: Changed from top_genes_idx to top_genes
    columns=top_variable_data.columns
)

Top variable genes shape: (3000, 202)

In [16]:
class RobustMahalanobisHDBSCAN:
    def __init__(self, min_cluster_size=5, min_samples=None):
        self.min_cluster_size = min_cluster_size
        self.min_samples = min_samples
        
    def _robust_mahalanobis(self, X):
        """Calculate pairwise Mahalanobis distances with regularization"""
        try:
            # Robust covariance estimation with increased support_fraction
            cov_estimator = MinCovDet(support_fraction=0.9).fit(X)
            cov = cov_estimator.covariance_
            
            # Regularization to ensure invertibility
            reg = 1e-6 * np.trace(cov)/cov.shape[0] * np.eye(cov.shape[0])
            cov_reg = cov + reg
            
            # Check condition number
            if fast_logdet(cov_reg) < -50:  # If nearly singular
                raise ValueError("Covariance matrix is nearly singular")
                
            cov_inv = np.linalg.inv(cov_reg)
            
            # Calculate distances using matrix operations
            diff = X[:, np.newaxis, :] - X[np.newaxis, :, :]
            dists = np.sqrt(np.einsum('...i,ij,...j->...', diff, cov_inv, diff))
            np.fill_diagonal(dists, 0)  # Ensure diagonal is exactly 0
            return dists
            
        except Exception as e:
            print(f"Mahalanobis calculation failed: {str(e)}")
            return None

    def fit(self, X):
        dist_matrix = self._robust_mahalanobis(X)
        if dist_matrix is None:
            # Fallback to Euclidean if Mahalanobis fails
            print("Using Euclidean as fallback")
            self.clusterer = hdbscan.HDBSCAN(
                min_cluster_size=self.min_cluster_size,
                min_samples=self.min_samples
            )
        else:
            self.clusterer = hdbscan.HDBSCAN(
                min_cluster_size=self.min_cluster_size,
                min_samples=self.min_samples,
                metric='precomputed'
            )
            
        self.labels_ = self.clusterer.fit_predict(dist_matrix if dist_matrix is not None else X)
        return self

# ----------------------------
# Metric Comparison
# ----------------------------
metrics = [
    ('euclidean', hdbscan.HDBSCAN(metric='euclidean')),
    ('manhattan', hdbscan.HDBSCAN(metric='manhattan')),
    ('correlation', hdbscan.HDBSCAN(metric='correlation')),
    ('mahalanobis', RobustMahalanobisHDBSCAN())
]

results = []
for name, clusterer in metrics:
    print(f"\n{'='*40}\nClustering with: {name.upper()}\n{'='*40}")
    
    try:
        start_time = time.time()
        
        if name == 'mahalanobis':
            print("Computing Mahalanobis distances...")
            clusterer.fit(top_variable_data.values)
            clusters = clusterer.labels_
        else:
            clusters = clusterer.fit_predict(top_variable_data)
            
        # Analysis
        unique_clusters = np.unique(clusters)
        n_clusters = len(unique_clusters) - 1  # Exclude noise (-1)
        noise_ratio = np.mean(clusters == -1)
        cluster_sizes = [np.sum(clusters == c) for c in unique_clusters if c != -1]
        
        results.append({
            'metric': name,
            'n_clusters': n_clusters,
            'noise_ratio': noise_ratio,
            'clusters': clusters,
            'cluster_sizes': cluster_sizes,
            'time': time.time() - start_time
        })
        
        print(f"Number of clusters: {n_clusters}")
        print(f"Noise ratio: {noise_ratio:.1%}")
        print(f"Cluster sizes: {sorted(cluster_sizes, reverse=True)}")
        print(f"Time elapsed: {results[-1]['time']:.2f} seconds")
        
    except Exception as e:
        print(f"Clustering failed: {str(e)}")
        results.append({
            'metric': name,
            'error': str(e),
            'clusters': None
        })

# ----------------------------
# Visualization
# ----------------------------
fig, axes = plt.subplots(2, 2, figsize=(16, 14))
axes = axes.ravel()

pca = PCA(n_components=2).fit_transform(top_variable_data)

for i, result in enumerate(results):
    ax = axes[i]
    
    if result['clusters'] is None:
        ax.text(0.5, 0.5, f"Failed:\n{result.get('error','')}", 
                ha='center', va='center', fontsize=12)
        ax.set_title(f"{result['metric'].upper()} - FAILED", fontsize=14)
        continue
        
    sc = ax.scatter(
        pca[:, 0], pca[:, 1],
        c=result['clusters'],
        cmap='tab20',
        alpha=0.7,
        s=15
    )
    
    title = (
        f"{result['metric'].upper()}\n"
        f"Clusters: {result['n_clusters']} | "
        f"Noise: {result['noise_ratio']:.1%}\n"
        f"Time: {result['time']:.2f}s"
    )
    ax.set_title(title, fontsize=12)
    
    # Add colorbar for cluster IDs
    plt.colorbar(sc, ax=ax, label='Cluster ID')

plt.tight_layout()
plt.savefig(f"{output_dir}/metric_comparison.png", dpi=300, bbox_inches='tight')
plt.close()

# ----------------------------
# Cluster Size Distribution Plot
# ----------------------------
plt.figure(figsize=(12, 6))
for result in results:
    if result['clusters'] is not None and result['cluster_sizes']:
        sizes = result['cluster_sizes']
        plt.plot(sorted(sizes, reverse=True), 'o-', label=result['metric'].upper())

plt.xlabel("Cluster Rank", fontsize=12)
plt.ylabel("Number of Genes", fontsize=12)
plt.title("Cluster Size Distribution by Distance Metric", fontsize=14)
plt.yscale('log')
plt.legend()
plt.grid(True, which="both", ls="--")
plt.savefig(f"{output_dir}/cluster_size_distribution.png", dpi=300, bbox_inches='tight')
plt.close()

# ----------------------------
# Save Results
# ----------------------------
for result in results:
    if result['clusters'] is not None:
        pd.DataFrame({
            'gene': top_variable_data.index,
            'cluster': result['clusters']
        }).to_csv(f"{output_dir}/clusters_{result['metric']}.csv", index=False)

# Save summary statistics
summary_data = []
for r in results:
    summary_data.append({
        'metric': r['metric'],
        'n_clusters': r.get('n_clusters', np.nan),
        'noise_ratio': r.get('noise_ratio', np.nan),
        'largest_cluster': max(r['cluster_sizes']) if 'cluster_sizes' in r and r['cluster_sizes'] else np.nan,
        'time_seconds': r.get('time', np.nan),
        'status': 'SUCCESS' if r['clusters'] is not None else 'FAILED'
    })

summary_df = pd.DataFrame(summary_data)
summary_df.to_csv(f"{output_dir}/summary_stats.csv", index=False)

print(f"\nAnalysis complete. Results saved to: {output_dir}")
print("\nSummary Statistics:")
print(summary_df.to_string(index=False))

========================================
Clustering with: EUCLIDEAN
========================================
Number of clusters: 5
Noise ratio: 8.4%
Cluster sizes: [2717, 11, 8, 6, 5]
Time elapsed: 4.39 seconds

========================================
Clustering with: MANHATTAN
========================================
Number of clusters: 12
Noise ratio: 44.2%
Cluster sizes: [1266, 186, 93, 35, 27, 14, 14, 10, 8, 7, 7, 6]
Time elapsed: 4.70 seconds

========================================
Clustering with: CORRELATION
========================================
Number of clusters: 10
Noise ratio: 33.6%
Cluster sizes: [1085, 664, 126, 28, 25, 20, 14, 13, 10, 7]
Time elapsed: 1.20 seconds

========================================
Clustering with: MAHALANOBIS
========================================
Computing Mahalanobis distances...

C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:753: UserWarning: The covariance matrix associated to your dataset is not full rank
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-894.899231369978338 > -925.210490210406874). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-925.052839275076508 > -927.784331163067236). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-958.854140245614417 > -959.541934137361181). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-925.985500716189676 > -948.434457226196969). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-925.846514800363138 > -926.890310900441136). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-861.063134918723676 > -919.756634399893301). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-834.175288879287450 > -891.411864451900556). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-904.595750108783932 > -927.065074149628344). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-894.499615242858226 > -923.533400135636612). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-899.222215714595336 > -932.248809491769066). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-899.887418905489767 > -929.119423936981434). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-904.299648001115429 > -921.934309753303978). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-869.519771958720867 > -897.835126901203125). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-900.928493929799743 > -919.663410211498103). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-907.872471743058668 > -936.229104961378084). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-878.435082733126819 > -912.616558561768898). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-890.398740900807297 > -903.243748212584478). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-878.832780713502984 > -898.453371555049557). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-919.738212021648224 > -920.416562430596400). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-910.050231104551244 > -910.405137224362420). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-911.001656429409650 > -937.182408306004845). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-905.775699652971070 > -931.933918671442598). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-904.769366387119021 > -933.792693521364072). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-918.197263236560843 > -946.540265253632924). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-913.757953317611396 > -933.548308495816173). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-881.218231034972064 > -914.285707154753482). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-936.267609722333759 > -943.031617289022847). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-928.614290048057796 > -930.417021921030710). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-892.624947169348388 > -920.374986955263125). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-924.440840549685845 > -948.997388983519159). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-960.168206478841853 > -962.811710377835311). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-932.503551385030164 > -937.659037732658476). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-883.116168123533271 > -931.209643731970118). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-915.982144890857739 > -936.517247879568799). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-921.736618573951205 > -949.688834621274054). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-887.780252556681603 > -896.316164535996563). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-882.620143998254775 > -939.809261510135457). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-924.551740563187877 > -952.566091477654709). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-915.478573036858279 > -937.393465950106020). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-917.778913136080632 > -944.900731077883620). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-918.405768965479979 > -944.392870222314968). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-942.514641532662836 > -943.105030865801837). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-879.288652609275346 > -934.027132874092104). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-893.141613849297869 > -915.202550366040668). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-910.234246022637308 > -932.913094706139304). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-920.515494474552270 > -950.385750239466688). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-913.958761695276849 > -933.084264226965388). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-891.472737308549995 > -905.532916823070082). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-883.834918032727046 > -948.369418432594671). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-881.871403797972562 > -935.640389560369272). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-918.945614167186022 > -924.166529371109277). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-916.610770392210043 > -935.048669671778953). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-921.948451989911177 > -923.592903922002051). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-892.105434679130099 > -950.820899182707421). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-919.039675530268255 > -948.574181496224924). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-819.047587968315611 > -822.541676523777028). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(

Mahalanobis calculation failed: Covariance matrix is nearly singular
Using Euclidean as fallback
Number of clusters: 5
Noise ratio: 8.4%
Cluster sizes: [2717, 11, 8, 6, 5]
Time elapsed: 24.21 seconds

Analysis complete. Results saved to: final_results/distance_metric_comparison_again_for5k_check/check

Summary Statistics:
     metric  n_clusters  noise_ratio  largest_cluster  time_seconds  status
  euclidean           5     0.084333             2717      4.391114 SUCCESS
  manhattan          12     0.442333             1266      4.698429 SUCCESS
correlation          10     0.336000             1085      1.200722 SUCCESS
mahalanobis           5     0.084333             2717     24.208442 SUCCESS

For 5000 top variable genes

Load the data and prepare the directories

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import time
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.covariance import MinCovDet
import hdbscan
from scipy import linalg

def fast_logdet(matrix):
    """Compute log determinant efficiently"""
    return 2 * np.sum(np.log(np.diag(linalg.cholesky(matrix))))

# Create output directory
output_dir = "final_results/distance_metric_comparison_again_for_5k_GENES/check"
os.makedirs(output_dir, exist_ok=True)

Data normalization and extraction of 5K variable genes

In [18]:

# 1. Data preparation
normalized_data = np.log2(filtered_df + 1)  # Log2 transform with pseudocount

# 2. Select top variable genes
gene_variability = normalized_data.std(axis=1)
top_genes = gene_variability.sort_values(ascending=False).head(5000).index
top_variable_data = normalized_data.loc[top_genes]

print(f"Top variable genes shape: {top_variable_data.shape}")

top_variable_data = pd.DataFrame(
    StandardScaler().fit_transform(top_variable_data),
    index=top_genes,  # CORRECTED: Changed from top_genes_idx to top_genes
    columns=top_variable_data.columns
)

Top variable genes shape: (5000, 202)

In [19]:
class RobustMahalanobisHDBSCAN:
    def __init__(self, min_cluster_size=5, min_samples=None):
        self.min_cluster_size = min_cluster_size
        self.min_samples = min_samples
        
    def _robust_mahalanobis(self, X):
        """Calculate pairwise Mahalanobis distances with regularization"""
        try:
            # Robust covariance estimation with increased support_fraction
            cov_estimator = MinCovDet(support_fraction=0.9).fit(X)
            cov = cov_estimator.covariance_
            
            # Regularization to ensure invertibility
            reg = 1e-6 * np.trace(cov)/cov.shape[0] * np.eye(cov.shape[0])
            cov_reg = cov + reg
            
            # Check condition number
            if fast_logdet(cov_reg) < -50:  # If nearly singular
                raise ValueError("Covariance matrix is nearly singular")
                
            cov_inv = np.linalg.inv(cov_reg)
            
            # Calculate distances using matrix operations
            diff = X[:, np.newaxis, :] - X[np.newaxis, :, :]
            dists = np.sqrt(np.einsum('...i,ij,...j->...', diff, cov_inv, diff))
            np.fill_diagonal(dists, 0)  # Ensure diagonal is exactly 0
            return dists
            
        except Exception as e:
            print(f"Mahalanobis calculation failed: {str(e)}")
            return None

    def fit(self, X):
        dist_matrix = self._robust_mahalanobis(X)
        if dist_matrix is None:
            # Fallback to Euclidean if Mahalanobis fails
            print("Using Euclidean as fallback")
            self.clusterer = hdbscan.HDBSCAN(
                min_cluster_size=self.min_cluster_size,
                min_samples=self.min_samples
            )
        else:
            self.clusterer = hdbscan.HDBSCAN(
                min_cluster_size=self.min_cluster_size,
                min_samples=self.min_samples,
                metric='precomputed'
            )
            
        self.labels_ = self.clusterer.fit_predict(dist_matrix if dist_matrix is not None else X)
        return self

# ----------------------------
# Metric Comparison
# ----------------------------
metrics = [
    ('euclidean', hdbscan.HDBSCAN(metric='euclidean')),
    ('manhattan', hdbscan.HDBSCAN(metric='manhattan')),
    ('correlation', hdbscan.HDBSCAN(metric='correlation')),
    ('mahalanobis', RobustMahalanobisHDBSCAN())
]

results = []
for name, clusterer in metrics:
    print(f"\n{'='*40}\nClustering with: {name.upper()}\n{'='*40}")
    
    try:
        start_time = time.time()
        
        if name == 'mahalanobis':
            print("Computing Mahalanobis distances...")
            clusterer.fit(top_variable_data.values)
            clusters = clusterer.labels_
        else:
            clusters = clusterer.fit_predict(top_variable_data)
            
        # Analysis
        unique_clusters = np.unique(clusters)
        n_clusters = len(unique_clusters) - 1  # Exclude noise (-1)
        noise_ratio = np.mean(clusters == -1)
        cluster_sizes = [np.sum(clusters == c) for c in unique_clusters if c != -1]
        
        results.append({
            'metric': name,
            'n_clusters': n_clusters,
            'noise_ratio': noise_ratio,
            'clusters': clusters,
            'cluster_sizes': cluster_sizes,
            'time': time.time() - start_time
        })
        
        print(f"Number of clusters: {n_clusters}")
        print(f"Noise ratio: {noise_ratio:.1%}")
        print(f"Cluster sizes: {sorted(cluster_sizes, reverse=True)}")
        print(f"Time elapsed: {results[-1]['time']:.2f} seconds")
        
    except Exception as e:
        print(f"Clustering failed: {str(e)}")
        results.append({
            'metric': name,
            'error': str(e),
            'clusters': None
        })

# ----------------------------
# Visualization
# ----------------------------
fig, axes = plt.subplots(2, 2, figsize=(16, 14))
axes = axes.ravel()

pca = PCA(n_components=2).fit_transform(top_variable_data)

for i, result in enumerate(results):
    ax = axes[i]
    
    if result['clusters'] is None:
        ax.text(0.5, 0.5, f"Failed:\n{result.get('error','')}", 
                ha='center', va='center', fontsize=12)
        ax.set_title(f"{result['metric'].upper()} - FAILED", fontsize=14)
        continue
        
    sc = ax.scatter(
        pca[:, 0], pca[:, 1],
        c=result['clusters'],
        cmap='tab20',
        alpha=0.7,
        s=15
    )
    
    title = (
        f"{result['metric'].upper()}\n"
        f"Clusters: {result['n_clusters']} | "
        f"Noise: {result['noise_ratio']:.1%}\n"
        f"Time: {result['time']:.2f}s"
    )
    ax.set_title(title, fontsize=12)
    
    # Add colorbar for cluster IDs
    plt.colorbar(sc, ax=ax, label='Cluster ID')

plt.tight_layout()
plt.savefig(f"{output_dir}/metric_comparison.png", dpi=300, bbox_inches='tight')
plt.close()

# ----------------------------
# Cluster Size Distribution Plot
# ----------------------------
plt.figure(figsize=(12, 6))
for result in results:
    if result['clusters'] is not None and result['cluster_sizes']:
        sizes = result['cluster_sizes']
        plt.plot(sorted(sizes, reverse=True), 'o-', label=result['metric'].upper())

plt.xlabel("Cluster Rank", fontsize=12)
plt.ylabel("Number of Genes", fontsize=12)
plt.title("Cluster Size Distribution by Distance Metric", fontsize=14)
plt.yscale('log')
plt.legend()
plt.grid(True, which="both", ls="--")
plt.savefig(f"{output_dir}/cluster_size_distribution.png", dpi=300, bbox_inches='tight')
plt.close()

# ----------------------------
# Save Results
# ----------------------------
for result in results:
    if result['clusters'] is not None:
        pd.DataFrame({
            'gene': top_variable_data.index,
            'cluster': result['clusters']
        }).to_csv(f"{output_dir}/clusters_{result['metric']}.csv", index=False)

# Save summary statistics
summary_data = []
for r in results:
    summary_data.append({
        'metric': r['metric'],
        'n_clusters': r.get('n_clusters', np.nan),
        'noise_ratio': r.get('noise_ratio', np.nan),
        'largest_cluster': max(r['cluster_sizes']) if 'cluster_sizes' in r and r['cluster_sizes'] else np.nan,
        'time_seconds': r.get('time', np.nan),
        'status': 'SUCCESS' if r['clusters'] is not None else 'FAILED'
    })

summary_df = pd.DataFrame(summary_data)
summary_df.to_csv(f"{output_dir}/summary_stats.csv", index=False)

print(f"\nAnalysis complete. Results saved to: {output_dir}")
print("\nSummary Statistics:")
print(summary_df.to_string(index=False))

========================================
Clustering with: EUCLIDEAN
========================================
Number of clusters: 2
Noise ratio: 4.0%
Cluster sizes: [4796, 6]
Time elapsed: 12.36 seconds

========================================
Clustering with: MANHATTAN
========================================
Number of clusters: 2
Noise ratio: 22.0%
Cluster sizes: [3896, 6]
Time elapsed: 11.52 seconds

========================================
Clustering with: CORRELATION
========================================
Number of clusters: 11
Noise ratio: 49.2%
Cluster sizes: [1273, 889, 153, 60, 56, 42, 25, 16, 13, 9, 5]
Time elapsed: 3.07 seconds

========================================
Clustering with: MAHALANOBIS
========================================
Computing Mahalanobis distances...

C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:753: UserWarning: The covariance matrix associated to your dataset is not full rank
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-903.793886105786214 > -918.215494810070027). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-903.980944325302858 > -925.641779579659897). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-913.626384535283250 > -932.233519396627571). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-878.291474260687096 > -908.501596879897534). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-918.167571267934136 > -934.920195173325510). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-868.615216989461828 > -889.509424994638266). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-927.350122660127113 > -932.068067517942154). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-869.814095893629883 > -892.301263586194068). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-897.736729349403049 > -897.896873202829511). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-904.950346380509814 > -926.482353486473130). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-915.154818284467979 > -928.852694227591314). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-911.719850262857221 > -932.136851616829972). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-876.274839931156862 > -904.023398478974627). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-860.423839162869285 > -916.959909898115484). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-895.087073000614851 > -913.546762303348828). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-862.839723308947327 > -890.048096639553023). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-884.631296615059455 > -914.497515914257406). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-911.364274521051470 > -915.631464395792932). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-886.616244296150967 > -905.998981085395599). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-922.704233728701183 > -938.108938267738608). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-883.154475138663315 > -914.173034792245858). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-918.305969877191274 > -938.507148201468226). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-957.089263707851273 > -958.435619971604524). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-906.136890886960373 > -932.106523564135273). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-918.231645653619125 > -948.869843590450614). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-879.328177269096955 > -929.401931259341950). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-879.497367146366514 > -902.550341652571433). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-917.639623449606461 > -920.377706439069129). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-881.840134247867923 > -906.162666368208420). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-913.643348674690856 > -948.722513098850754). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-900.237047049625971 > -929.941482822922922). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-874.336762960865713 > -910.220665572454323). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-903.434916434889374 > -903.841142356125488). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-911.496474038510883 > -942.031165122029279). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-871.635363250942305 > -890.443021952181880). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-870.187867217935946 > -894.333743611617138). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-913.158010645347645 > -930.849947757749192). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-942.824525778847942 > -946.044232903754050). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-912.441462205910966 > -926.279594973462849). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-906.393622929198727 > -944.072477407056340). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-878.083915942527142 > -911.528820429831740). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-870.443752318979023 > -897.138063320508309). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-910.478828314570251 > -929.706615104895491). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-904.846060163288939 > -938.855380188311415). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-911.380751810189736 > -914.353915983901402). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-903.371117096771059 > -930.456994942588040). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-915.582660674303611 > -927.126646375500854). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-906.092822294078474 > -931.024379164962511). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-904.394535598010407 > -922.685678512916979). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-902.911768347346083 > -936.338267422566332). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-922.927612094656297 > -948.322531751780389). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-928.189611711869702 > -941.197792352136275). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-936.199144613206386 > -947.653454021027528). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-903.220212677427639 > -921.993109233399423). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-894.314182249940927 > -894.758944874082090). You may want to try with a higher value of support_fraction (current value: 0.901).
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\covariance\_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-823.009838816955039 > -853.714360350579227). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(

Mahalanobis calculation failed: Covariance matrix is nearly singular
Using Euclidean as fallback
Number of clusters: 2
Noise ratio: 4.0%
Cluster sizes: [4796, 6]
Time elapsed: 44.68 seconds

Analysis complete. Results saved to: final_results/distance_metric_comparison_again_for_5k_GENES/check

Summary Statistics:
     metric  n_clusters  noise_ratio  largest_cluster  time_seconds  status
  euclidean           2       0.0396             4796     12.361816 SUCCESS
  manhattan           2       0.2196             3896     11.518691 SUCCESS
correlation          11       0.4918             1273      3.069968 SUCCESS
mahalanobis           2       0.0396             4796     44.681585 SUCCESS

For complete dataset 
data normalization and directory preparations

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import time
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.covariance import MinCovDet
import hdbscan
from scipy import linalg

def fast_logdet(matrix):
    """Compute log determinant efficiently"""
    return 2 * np.sum(np.log(np.diag(linalg.cholesky(matrix))))

# Create output directory
output_dir = "final_results/complete_data_distance_comparison"
os.makedirs(output_dir, exist_ok=True)

# 1. Data preparation - Use complete data instead of top variable genes
normalized_data = np.log2(filtered_df + 1)  # Log2 transform with pseudocount

print(f"Complete data shape: {normalized_data.shape}")

# 2. Z-score normalization on complete data
normalized_data = pd.DataFrame(
    StandardScaler().fit_transform(normalized_data),
    index=normalized_data.index,  # Keep original gene names
    columns=normalized_data.columns
)

In [18]:
class RobustMahalanobisHDBSCAN:
    def __init__(self, min_cluster_size=5, min_samples=None):
        self.min_cluster_size = min_cluster_size
        self.min_samples = min_samples
        
    def _robust_mahalanobis(self, X):
        """Calculate pairwise Mahalanobis distances with regularization"""
        try:
            # Robust covariance estimation with increased support_fraction
            cov_estimator = MinCovDet(support_fraction=0.9).fit(X)
            cov = cov_estimator.covariance_
            
            # Regularization to ensure invertibility
            reg = 1e-6 * np.trace(cov)/cov.shape[0] * np.eye(cov.shape[0])
            cov_reg = cov + reg
            
            # Check condition number
            if fast_logdet(cov_reg) < -50:  # If nearly singular
                raise ValueError("Covariance matrix is nearly singular")
                
            cov_inv = np.linalg.inv(cov_reg)
            
            # Calculate distances using matrix operations
            diff = X[:, np.newaxis, :] - X[np.newaxis, :, :]
            dists = np.sqrt(np.einsum('...i,ij,...j->...', diff, cov_inv, diff))
            np.fill_diagonal(dists, 0)  # Ensure diagonal is exactly 0
            return dists
            
        except Exception as e:
            print(f"Mahalanobis calculation failed: {str(e)}")
            return None

    def fit(self, X):
        dist_matrix = self._robust_mahalanobis(X)
        if dist_matrix is None:
            # Fallback to Euclidean if Mahalanobis fails
            print("Using Euclidean as fallback")
            self.clusterer = hdbscan.HDBSCAN(
                min_cluster_size=self.min_cluster_size,
                min_samples=self.min_samples
            )
        else:
            self.clusterer = hdbscan.HDBSCAN(
                min_cluster_size=self.min_cluster_size,
                min_samples=self.min_samples,
                metric='precomputed'
            )
            
        self.labels_ = self.clusterer.fit_predict(dist_matrix if dist_matrix is not None else X)
        return self

# ----------------------------
# Metric Comparison on Complete Data
# ----------------------------
metrics = [
    ('euclidean', hdbscan.HDBSCAN(metric='euclidean')),
    ('manhattan', hdbscan.HDBSCAN(metric='manhattan')),
    ('correlation', hdbscan.HDBSCAN(metric='correlation')),
    ('mahalanobis', RobustMahalanobisHDBSCAN())
]

results = []
for name, clusterer in metrics:
    print(f"\n{'='*40}\nClustering with: {name.upper()}\n{'='*40}")
    
    try:
        start_time = time.time()
        
        if name == 'mahalanobis':
            print("Computing Mahalanobis distances...")
            clusterer.fit(normalized_data.values)
            clusters = clusterer.labels_
        else:
            clusters = clusterer.fit_predict(normalized_data)
            
        # Analysis
        unique_clusters = np.unique(clusters)
        n_clusters = len(unique_clusters) - 1  # Exclude noise (-1)
        noise_ratio = np.mean(clusters == -1)
        cluster_sizes = [np.sum(clusters == c) for c in unique_clusters if c != -1]
        
        results.append({
            'metric': name,
            'n_clusters': n_clusters,
            'noise_ratio': noise_ratio,
            'clusters': clusters,
            'cluster_sizes': cluster_sizes,
            'time': time.time() - start_time
        })
        
        print(f"Number of clusters: {n_clusters}")
        print(f"Noise ratio: {noise_ratio:.1%}")
        print(f"Cluster sizes: {sorted(cluster_sizes, reverse=True)}")
        print(f"Time elapsed: {results[-1]['time']:.2f} seconds")
        
    except Exception as e:
        print(f"Clustering failed: {str(e)}")
        results.append({
            'metric': name,
            'error': str(e),
            'clusters': None
        })

# ----------------------------
# Visualization
# ----------------------------
fig, axes = plt.subplots(2, 2, figsize=(16, 14))
axes = axes.ravel()

# Use PCA for visualization (may take longer with complete data)
print("Computing PCA for visualization...")
pca = PCA(n_components=2).fit_transform(normalized_data)

for i, result in enumerate(results):
    ax = axes[i]
    
    if result['clusters'] is None:
        ax.text(0.5, 0.5, f"Failed:\n{result.get('error','')}", 
                ha='center', va='center', fontsize=12)
        ax.set_title(f"{result['metric'].upper()} - FAILED", fontsize=14)
        continue
        
    sc = ax.scatter(
        pca[:, 0], pca[:, 1],
        c=result['clusters'],
        cmap='tab20',
        alpha=0.7,
        s=15
    )
    
    title = (
        f"{result['metric'].upper()}\n"
        f"Clusters: {result['n_clusters']} | "
        f"Noise: {result['noise_ratio']:.1%}\n"
        f"Time: {result['time']:.2f}s"
    )
    ax.set_title(title, fontsize=12)
    
    # Add colorbar for cluster IDs
    plt.colorbar(sc, ax=ax, label='Cluster ID')

plt.tight_layout()
plt.savefig(f"{output_dir}/complete_data_metric_comparison.png", dpi=300, bbox_inches='tight')
plt.close()

# ----------------------------
# Cluster Size Distribution Plot
# ----------------------------
plt.figure(figsize=(12, 6))
for result in results:
    if result['clusters'] is not None and result['cluster_sizes']:
        sizes = result['cluster_sizes']
        plt.plot(sorted(sizes, reverse=True), 'o-', label=result['metric'].upper())

plt.xlabel("Cluster Rank", fontsize=12)
plt.ylabel("Number of Genes", fontsize=12)
plt.title("Cluster Size Distribution by Distance Metric (Complete Data)", fontsize=14)
plt.yscale('log')
plt.legend()
plt.grid(True, which="both", ls="--")
plt.savefig(f"{output_dir}/complete_data_cluster_size_distribution.png", dpi=300, bbox_inches='tight')
plt.close()

# ----------------------------
# Save Results
# ----------------------------
for result in results:
    if result['clusters'] is not None:
        pd.DataFrame({
            'gene': normalized_data.index,
            'cluster': result['clusters']
        }).to_csv(f"{output_dir}/complete_data_clusters_{result['metric']}.csv", index=False)

# Save summary statistics
summary_data = []
for r in results:
    summary_data.append({
        'metric': r['metric'],
        'n_clusters': r.get('n_clusters', np.nan),
        'noise_ratio': r.get('noise_ratio', np.nan),
        'largest_cluster': max(r['cluster_sizes']) if 'cluster_sizes' in r and r['cluster_sizes'] else np.nan,
        'time_seconds': r.get('time', np.nan),
        'status': 'SUCCESS' if r['clusters'] is not None else 'FAILED'
    })

summary_df = pd.DataFrame(summary_data)
summary_df.to_csv(f"{output_dir}/complete_data_summary_stats.csv", index=False)

print(f"\nAnalysis complete. Results saved to: {output_dir}")
print("\nSummary Statistics:")
print(summary_df.to_string(index=False))

Complete data shape: (27038, 202)

========================================
Clustering with: EUCLIDEAN
========================================

/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/utils/deprecation.py:132: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/utils/deprecation.py:132: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Number of clusters: 63
Noise ratio: 58.3%
Cluster sizes: [np.int64(10357), np.int64(131), np.int64(48), np.int64(43), np.int64(36), np.int64(30), np.int64(30), np.int64(27), np.int64(27), np.int64(25), np.int64(24), np.int64(22), np.int64(19), np.int64(19), np.int64(17), np.int64(17), np.int64(15), np.int64(14), np.int64(14), np.int64(13), np.int64(13), np.int64(13), np.int64(12), np.int64(12), np.int64(12), np.int64(12), np.int64(12), np.int64(11), np.int64(11), np.int64(11), np.int64(10), np.int64(10), np.int64(10), np.int64(10), np.int64(9), np.int64(9), np.int64(9), np.int64(9), np.int64(9), np.int64(8), np.int64(8), np.int64(8), np.int64(8), np.int64(8), np.int64(7), np.int64(7), np.int64(7), np.int64(7), np.int64(7), np.int64(7), np.int64(6), np.int64(6), np.int64(6), np.int64(6), np.int64(6), np.int64(6), np.int64(5), np.int64(5), np.int64(5), np.int64(5), np.int64(5), np.int64(5), np.int64(5)]
Time elapsed: 87.07 seconds

========================================
Clustering with: MANHATTAN
========================================

/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/utils/deprecation.py:132: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/utils/deprecation.py:132: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Number of clusters: 62
Noise ratio: 60.0%
Cluster sizes: [np.int64(9945), np.int64(116), np.int64(48), np.int64(43), np.int64(35), np.int64(34), np.int64(30), np.int64(27), np.int64(26), np.int64(22), np.int64(20), np.int64(17), np.int64(17), np.int64(17), np.int64(16), np.int64(15), np.int64(14), np.int64(14), np.int64(14), np.int64(13), np.int64(13), np.int64(12), np.int64(12), np.int64(12), np.int64(12), np.int64(12), np.int64(11), np.int64(11), np.int64(10), np.int64(10), np.int64(10), np.int64(9), np.int64(9), np.int64(9), np.int64(9), np.int64(9), np.int64(9), np.int64(9), np.int64(8), np.int64(8), np.int64(8), np.int64(8), np.int64(8), np.int64(7), np.int64(7), np.int64(7), np.int64(7), np.int64(7), np.int64(6), np.int64(6), np.int64(6), np.int64(6), np.int64(6), np.int64(6), np.int64(6), np.int64(6), np.int64(6), np.int64(6), np.int64(5), np.int64(5), np.int64(5), np.int64(5)]
Time elapsed: 94.60 seconds

========================================
Clustering with: CORRELATION
========================================

/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/utils/deprecation.py:132: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/utils/deprecation.py:132: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Number of clusters: 76
Noise ratio: 86.7%
Cluster sizes: [np.int64(1929), np.int64(184), np.int64(156), np.int64(135), np.int64(131), np.int64(62), np.int64(58), np.int64(51), np.int64(50), np.int64(48), np.int64(43), np.int64(34), np.int64(33), np.int64(27), np.int64(27), np.int64(25), np.int64(25), np.int64(24), np.int64(20), np.int64(18), np.int64(17), np.int64(17), np.int64(17), np.int64(17), np.int64(15), np.int64(14), np.int64(14), np.int64(14), np.int64(13), np.int64(13), np.int64(13), np.int64(13), np.int64(13), np.int64(12), np.int64(12), np.int64(12), np.int64(12), np.int64(11), np.int64(11), np.int64(10), np.int64(10), np.int64(10), np.int64(10), np.int64(10), np.int64(9), np.int64(9), np.int64(9), np.int64(9), np.int64(9), np.int64(9), np.int64(9), np.int64(9), np.int64(8), np.int64(8), np.int64(8), np.int64(7), np.int64(7), np.int64(7), np.int64(7), np.int64(7), np.int64(7), np.int64(6), np.int64(6), np.int64(6), np.int64(6), np.int64(6), np.int64(6), np.int64(5), np.int64(5), np.int64(5), np.int64(5), np.int64(5), np.int64(5), np.int64(5), np.int64(5), np.int64(5)]
Time elapsed: 36.76 seconds

========================================
Clustering with: MAHALANOBIS
========================================
Computing Mahalanobis distances...

/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:749: UserWarning: The covariance matrix associated to your dataset is not full rank
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1146.262461109045489 > -1148.793936256348161). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1072.265073565933790 > -1076.612386363824044). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1094.371626210581553 > -1097.938174826049362). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1112.681795335304514 > -1114.126686013818244). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1033.781583842665441 > -1046.012199804116335). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1027.764135489158662 > -1054.588883811795085). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1070.280452741681074 > -1070.786168611024323). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1067.027015745299195 > -1093.397599708478083). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1019.714017759733679 > -1038.354208179416219). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1097.578416377856456 > -1107.513393097819744). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1065.255801259510235 > -1071.057660803961426). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1027.186238765809549 > -1059.418233495328877). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1047.683474039796920 > -1056.778606043801574). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1134.858141392821381 > -1135.051504504094964). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1083.554907676835228 > -1086.101294791266582). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1091.122242845914116 > -1102.976308451857221). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1041.302410295018262 > -1068.357469770952548). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1149.421797571865682 > -1149.931874613445871). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1084.420941297249556 > -1085.178249629699849). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1112.167434553492967 > -1112.634660745229439). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1051.953933326821925 > -1075.892176780777845). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1084.879378958417419 > -1120.080197724626032). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1092.343572056768380 > -1093.578073264945488). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1099.902331860153254 > -1102.803346037125493). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1100.837423552773998 > -1105.967587369614193). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1127.345853720118839 > -1145.031582601017135). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1074.207048618245153 > -1075.976695029450184). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1081.487939657801689 > -1099.656044657058374). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1089.731756258448968 > -1090.132579996046616). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1043.367085759734209 > -1076.743736348380025). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1081.184583748903378 > -1111.310125324331921). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1060.290545462679574 > -1096.692064922752479). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1083.198614416113742 > -1102.913499612864598). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1111.022042166009442 > -1136.460458276911368). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1079.511775890482340 > -1102.340908827983412). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1074.712324607607343 > -1091.941243444582142). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1075.991437499123549 > -1078.044402875456626). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1100.005605001851336 > -1112.349864696881923). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1051.694011699235034 > -1076.502957205589837). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1068.661490712040631 > -1078.519090940572141). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1075.709789259984518 > -1126.976424683499999). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1118.920201603419855 > -1121.336638851410271). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1055.844251008329366 > -1065.711403368900619). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1043.853904657040175 > -1086.315866447956751). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1088.329086452451747 > -1113.830317073449123). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1087.648682814536642 > -1088.320117869772503). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1089.038115850483791 > -1106.758095353379986). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1176.436090145591834 > -1177.632159058478010). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1060.817622336333216 > -1081.227141829341690). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1067.187651482100591 > -1079.253624486037324). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1079.575621574633715 > -1084.822335049684852). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1096.881149697770525 > -1106.926840620061284). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1075.859224006650265 > -1077.490553994602806). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1080.870979985508484 > -1082.989043001765367). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1090.848878077960080 > -1096.214438770336756). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
/home/shafeeq/Downloads/yes/lib/python3.13/site-packages/sklearn/covariance/_robust_covariance.py:185: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1068.578638014650096 > -1098.886252431847879). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(

Mahalanobis calculation failed: Covariance matrix is nearly singular
Using Euclidean as fallback
Number of clusters: 63
Noise ratio: 58.3%
Cluster sizes: [np.int64(10357), np.int64(131), np.int64(48), np.int64(43), np.int64(36), np.int64(30), np.int64(30), np.int64(27), np.int64(27), np.int64(25), np.int64(24), np.int64(22), np.int64(19), np.int64(19), np.int64(17), np.int64(17), np.int64(15), np.int64(14), np.int64(14), np.int64(13), np.int64(13), np.int64(13), np.int64(12), np.int64(12), np.int64(12), np.int64(12), np.int64(12), np.int64(11), np.int64(11), np.int64(11), np.int64(10), np.int64(10), np.int64(10), np.int64(10), np.int64(9), np.int64(9), np.int64(9), np.int64(9), np.int64(9), np.int64(8), np.int64(8), np.int64(8), np.int64(8), np.int64(8), np.int64(7), np.int64(7), np.int64(7), np.int64(7), np.int64(7), np.int64(7), np.int64(6), np.int64(6), np.int64(6), np.int64(6), np.int64(6), np.int64(6), np.int64(5), np.int64(5), np.int64(5), np.int64(5), np.int64(5), np.int64(5), np.int64(5)]
Time elapsed: 107.10 seconds
Computing PCA for visualization...

Analysis complete. Results saved to: final_results/complete_data_distance_comparison

Summary Statistics:
     metric  n_clusters  noise_ratio  largest_cluster  time_seconds  status
  euclidean          63     0.582624            10357     87.073885 SUCCESS
  manhattan          62     0.599601             9945     94.599330 SUCCESS
correlation          76     0.866521             1929     36.763091 SUCCESS
mahalanobis          63     0.582624            10357    107.104773 SUCCESS